# Generated by Django 5.0.6 on 2026-05-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_initial", models.FloatField()),
                ("quantity_current", models.FloatField()),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("received_at", models.DateTimeField()),
                ("expiry_date_manual", models.DateField(blank=True, null=True)),
                ("Q_current", models.FloatField(default=1.0)),
                ("last_calculated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("consumed", "Consumed"),
                            ("wasted", "Wasted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ConsumptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("cooking", "Cooking"),
                            ("waste", "Waste"),
                            ("return", "Return"),
                        ],
                        default="cooking",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("l", "Liter"),
                            ("piece", "Piece"),
                        ],
                        default="kg",
                        max_length=8,
                    ),
                ),
                ("E_a", models.FloatField(help_text="Activation energy, kJ/mol")),
                (
                    "A_coefficient",
                    models.FloatField(help_text="Pre-exponential factor (1/hour)"),
                ),
                (
                    "T_optimal_min",
                    models.FloatField(help_text="Optimal storage temperature min, °C"),
                ),
                (
                    "T_optimal_max",
                    models.FloatField(help_text="Optimal storage temperature max, °C"),
                ),
                (
                    "Q_critical",
                    models.FloatField(
                        default=0.6, help_text="Critical quality threshold"
                    ),
                ),
                ("shelf_life_days_at_4C", models.PositiveIntegerField(default=7)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_templates/"
                    ),
                ),
            ],
        ),
    ]
