# Generated by Django 5.0.6 on 2026-05-16 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consumptionlog",
            name="used_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.category",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="product_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="inventory.producttemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["restaurant", "status", "Q_current"],
                name="inventory_b_restaur_d6e1cb_idx",
            ),
        ),
    ]
