# Generated by Django 5.0.6 on 2026-05-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttemplate",
            options={"ordering": ["name"]},
        ),
    ]
