# Generated by Django 5.0.6 on 2026-05-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("tax_id", models.CharField(blank=True, max_length=32)),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                        ],
                        default="free",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("fridge", "Fridge"),
                            ("freezer", "Freezer"),
                            ("dry", "Dry storage"),
                        ],
                        default="fridge",
                        max_length=16,
                    ),
                ),
                ("target_temp_min", models.FloatField(default=0)),
                ("target_temp_max", models.FloatField(default=4)),
                ("current_temp", models.FloatField(blank=True, null=True)),
                ("sensor_id", models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
