# Generated by Django 5.0.6 on 2026-05-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="simulate_sensor",
            field=models.BooleanField(
                default=False, help_text="Generate synthetic sensor readings every 30s."
            ),
        ),
    ]
