# Generated by Django 5.0.6 on 2026-05-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_storage_simulate_sensor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurant",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="storage",
            options={"ordering": ["restaurant_id", "name"]},
        ),
    ]
