# Generated by Django 5.0.6 on 2026-05-16 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temperaturereading",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
