# Generated by Django 5.0.6 on 2026-05-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_received_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_consumed_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_wasted_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("waste_percentage", models.FloatField(default=0)),
                (
                    "money_saved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("pdf_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-period_start"],
            },
        ),
    ]
