# Generated by Django 5.0.6 on 2026-05-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyreport",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_reports",
                to="restaurants.restaurant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyreport",
            unique_together={("restaurant", "period_start")},
        ),
    ]
